version: "3.1"
services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: etsangatsangana
      POSTGRES_PASSWORD: vinamaster
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: andovinamaster@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    ports:
      - "98:80"
      