export default MyData = [
    { 
      "id": "1",
      "name": "Nuggets",
      "image": require('../assets/MyImages/nuggets.png'),
      "date": "12/05/2022",
      "details": "Deux nuggets chez Chicky",
      "prix": "2.000 ariary",
    }, 
    { 
      "id": "2",
      "name": "Transport",
      "image": require('../assets/MyImages/transport.png'),
      "date": "02/10/2022",
      "details": "Deux places pour Antsirabe",
      "prix": "3.0000 ariary",
    }, 
    { 
      "id": "3",
      "name": "Hotel",
      "image": require('../assets/MyImages/hotel.png'),
      "date": "15/02/2021",
      "details": "Chambre double pour deux personne à l'hotêl Carlton",
      "prix": "180.000 ariary",
    }, 
    { 
      "id": "4",
      "name": "Hotel",
      "image": require('../assets/MyImages/hotel.png'),
      "date": "15/02/2021",
      "details": "Chambre double pour deux personne à l'hotêl Carlton",
      "prix": "180.000 ariary",
    }, 
    { 
      "id": "5",
      "name": "Hotel",
      "image": require('../assets/MyImages/hotel.png'),
      "date": "15/02/2021",
      "details": "Chambre double pour deux personne à l'hotêl Carlton",
      "prix": "180.000 ariary",
    }, 
  ];